#!/usr/bin/env python3
"""Generate the interface control document by asking a running image.

The parameter tables and the command registry already carry everything the
document needs, and the image can list them, so the document is generated
rather than written: a service added without one shows up as a diff instead of
as prose nobody updated.
"""

import argparse
import difflib
import os
import pathlib
import re
import subprocess
import sys
import tempfile

ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")
PROMPT = re.compile(r"^kfsw:[^$]*\$\s*")
TABLE_ROW = re.compile(
    r"^\s*(?P<id>\d+)\s+(?P<layer>\w+)\s+(?P<name>\S+)\s+(?P<params>\d+)\s+"
    r"(?P<kept>\d+)\s+(?P<holds>.*)$"
)
COMMAND_ROW = re.compile(r"^(?P<id>\d+)\s+(?P<name>\S+)\s+flags=(?P<flags>0x[0-9a-f]+)$")

# A command may only be invoked by something that already holds the right to.
MUTATING = 0x1


def ask(image, flash, command, seconds):
    """Run the image, send one command, and return its output lines."""
    result = subprocess.run(
        [
            str(image),
            "--uart_stdinout",
            "--no-color",
            f"--stop_at={seconds}",
            f"-flash={flash}",
        ],
        input=f"{command}\n",
        capture_output=True,
        text=True,
        timeout=seconds + 30,
    )
    lines = []
    for line in result.stdout.splitlines():
        line = PROMPT.sub("", ANSI.sub("", line)).rstrip()
        if line:
            lines.append(line)
    return lines


def parse_tables(lines):
    tables = []
    for line in lines:
        match = TABLE_ROW.match(line)
        if match:
            tables.append(match.groupdict())
    return tables


def parse_parameters(lines):
    """Rows are aligned, and the description is last so it may hold spaces."""
    parameters = []
    for line in lines:
        fields = line.split(None, 6)
        if len(fields) < 6 or not fields[1].startswith("0x"):
            continue
        parameters.append(
            {
                "table": fields[0],
                "offset": fields[1],
                "name": fields[2],
                "type": fields[3],
                "mode": fields[4],
                "unit": fields[5],
                "description": fields[6] if len(fields) > 6 else "",
            }
        )
    return parameters


def parse_commands(lines):
    commands = []
    for line in lines:
        match = COMMAND_ROW.match(line)
        if match:
            commands.append(
                {
                    "id": match["id"],
                    "name": match["name"],
                    "flags": int(match["flags"], 16),
                    "args": "",
                    "help": "",
                }
            )
        elif commands and line.startswith("args:"):
            commands[-1]["args"] = line[len("args:") :].strip()
        elif commands and line.startswith("help:"):
            commands[-1]["help"] = line[len("help:") :].strip()
    return commands


def cell(text):
    """A pipe would end the column, and an empty cell reads as a mistake."""
    return text.replace("|", "\\|") if text and text != "-" else "-"


def render(tables, parameters, commands):
    out = []
    out.append("# Interface control document {#icd}")
    out.append("")
    out.append(
        "Every parameter and command the reference image carries. This page is "
        "generated by asking a running `linux` image, so it cannot describe "
        "something the firmware does not have."
    )
    out.append("")
    out.append(
        "The mode column is what the parameter service enforces: `r` is read "
        "only, `w` is writable, and `b` means the value is kept across a reset."
    )
    out.append("")
    out.append("## Parameter tables")
    out.append("")
    out.append("| Table | Layer | Name | Parameters | Kept | Holds |")
    out.append("| --- | --- | --- | --- | --- | --- |")
    for table in tables:
        out.append(
            f"| {table['id']} | {table['layer']} | `{table['name']}` | "
            f"{table['params']} | {table['kept']} | {cell(table['holds'])} |"
        )
    out.append("")

    by_table = {}
    for parameter in parameters:
        by_table.setdefault(parameter["table"], []).append(parameter)
    for table in tables:
        rows = by_table.get(table["name"], [])
        if not rows:
            continue
        out.append(f"### {table['name']} ({table['id']})")
        out.append("")
        out.append("| Offset | Name | Type | Mode | Unit | Description |")
        out.append("| --- | --- | --- | --- | --- | --- |")
        for row in rows:
            out.append(
                f"| {row['offset']} | `{row['name']}` | {row['type']} | "
                f"{row['mode']} | {cell(row['unit'])} | {cell(row['description'])} |"
            )
        out.append("")

    out.append("## Commands")
    out.append("")
    out.append("| ID | Name | Arguments | Changes state | Description |")
    out.append("| --- | --- | --- | --- | --- |")
    for command in sorted(commands, key=lambda entry: int(entry["id"])):
        mutating = "yes" if command["flags"] & MUTATING else "no"
        out.append(
            f"| {command['id']} | `{command['name']}` | {cell(command['args'])} | "
            f"{mutating} | {cell(command['help'])} |"
        )
    out.append("")
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare with the committed page and fail on a difference",
    )
    parser.add_argument("--seconds", type=float, default=12.0)
    arguments = parser.parse_args()

    repository = pathlib.Path(__file__).resolve().parents[2]
    workspace = repository.parent
    output_root = pathlib.Path(os.environ.get("KFSW_OUTPUT_ROOT", workspace / "build"))
    image = output_root / "linux" / "zephyr" / "zephyr.exe"
    page = repository / "docs" / "icd.md"

    if not image.is_file():
        print(f"ERROR: the linux image is missing: {image}")
        print("Build it with ./k-fsw/tools/build.sh linux")
        return 1

    # An incremental build keeps whatever was configured before it, and a test
    # build carries parameter fixtures. Either one produces a document that
    # describes something nobody ships, so refuse the image instead.
    configuration = image.parent / ".config"
    if configuration.is_file():
        if "CONFIG_KFSW_PARAM_TEST_DEFINITIONS=y" in configuration.read_text():
            print("ERROR: this image carries the parameter test fixtures")
            print("Rebuild it clean: KFSW_PRISTINE=always ./k-fsw/tools/build.sh linux")
            return 1

    with tempfile.TemporaryDirectory() as scratch:
        flash = pathlib.Path(scratch) / "icd-flash.bin"
        tables = parse_tables(ask(image, flash, "param tables", arguments.seconds))
        parameters = parse_parameters(ask(image, flash, "param describe", arguments.seconds))
        commands = parse_commands(ask(image, flash, "cmd describe", arguments.seconds))

    if not tables or not parameters or not commands:
        print(
            f"ERROR: the image answered with {len(tables)} tables, "
            f"{len(parameters)} parameters and {len(commands)} commands"
        )
        return 1

    # The table summary counts the parameters it holds, so a listing cut short
    # is caught here rather than published as a document missing rows.
    expected = sum(int(table["params"]) for table in tables)
    if expected != len(parameters):
        print(f"ERROR: the tables hold {expected} parameters but {len(parameters)} were listed")
        return 1

    # Nothing version-stamped goes on the page: the committed copy has to
    # match a regeneration exactly, or the check fails on every commit.
    document = render(tables, parameters, commands)

    if arguments.check:
        if not page.is_file():
            print(f"ERROR: {page} does not exist; run this without --check")
            return 1
        current = page.read_text()
        if current != document:
            print(f"ERROR: {page.name} does not match the image")
            sys.stdout.writelines(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    document.splitlines(keepends=True),
                    fromfile="committed",
                    tofile="image",
                )
            )
            return 1
        print(f"ICD RESULT: PASS ({len(parameters)} parameters, {len(commands)} commands)")
        return 0

    page.write_text(document)
    print(f"ICD: wrote {page} ({len(parameters)} parameters, {len(commands)} commands)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
