manifest:
  version: "1.2"

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

    - name: kfsw
      url-base: https://github.com/dgonzalez97

    - name: libcsp
      url-base: https://github.com/libcsp

    - name: spaceinventor
      url-base: https://github.com/spaceinventor

  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v4.4.0
      path: zephyr
      import: true

    - name: kfsw-platform
      remote: kfsw
      revision: f8c72173a4ed6346663fe57b27264844f87cbdd1
      path: kfsw-platform

    - name: kfsw-services
      remote: kfsw
      revision: 4f1a5bf6538489cdb721a5ce57f26045ed36c016
      path: kfsw-services

    - name: kfsw-comms
      remote: kfsw
      revision: 24cc78e9055f08c199e53a55fec3bcc3174f04bc
      path: kfsw-comms

    - name: kfsw-modules
      remote: kfsw
      revision: e762190542aa4a94e01d00ea485ad29d396cbad1
      path: kfsw-modules

    - name: libcsp
      remote: libcsp
      revision: 097a039701c85e4ceb98e91f380810662e23878a
      path: kfsw-comms/third_party/libcsp

    - name: libparam
      remote: spaceinventor
      revision: c296dfb6055a3c360f44dcbbd6ad108e98c76640
      path: kfsw-services/third_party/libparam

  self:
    path: k-fsw
