manifest:
  version: "1.2"

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

    - name: kfsw
      url-base: https://github.com/dgonzalez97

    - name: libcsp
      url-base: https://github.com/libcsp

  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v4.4.0
      path: zephyr
      import: true

    - name: kfsw-platform
      remote: kfsw
      revision: 45196b2cccf87d174af38c38fd5e327fd5eeb3ad
      path: kfsw-platform

    - name: kfsw-services
      remote: kfsw
      revision: a7982a90b29bdefec4d3e4ebf9b166b7ae3f4d2e
      path: kfsw-services

    - name: kfsw-comms
      remote: kfsw
      revision: 1ba3c2a30c80be1e608d19c90492d0a878ef3db2
      path: kfsw-comms

    - name: libcsp
      remote: libcsp
      revision: 097a039701c85e4ceb98e91f380810662e23878a
      path: kfsw-comms/third_party/libcsp

  self:
    path: k-fsw
