CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_KFSW_LOG_MIN_LEVEL=1

CONFIG_KFSW_DEBUG_SHELL=y

CONFIG_HWINFO=y

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_KFSW_STORAGE=y

CONFIG_ASSERT=y

CONFIG_MAIN_STACK_SIZE=2048
