#!/usr/bin/env python3
"""Pull housekeeping from a node and hand it to Yamcs.

Housekeeping answers when asked, so something on the ground has to do the
asking. This is that: a CSP client over a KISS serial link, small enough to
read in one sitting, that requests samples and forwards each one to a Yamcs UDP
telemetry link.

A node can also be told to beacon, putting its newest sample on the link
unasked. That frame is the one a request gets, from the same port, so --listen
records it with the same decoder and never transmits.

It forwards frames byte for byte and decodes nothing. What a value means lives
in the mission database, generated by hk-report.py from the same file that told
the node what to collect, so there is one decoder rather than two that can
disagree.

Point it at a pseudo-terminal for a hosted node:

    ./tools/kfsw-linux run              # note the uart_1 pseudotty it prints
    tools/ground/hk-bridge.py --device /dev/pts/7 --node 1 --report 0

or at the radio for the bench:

    tools/ground/hk-bridge.py --device "$KGROUND_HOLYBRO_DEVICE" \\
        --baud 57600 --node 2 --report 0
"""

import argparse
import collections
import socket
import struct
import sys
import time

import serial

# KISS, as libcsp frames it: a start, the escaped frame, and an end.
FEND = 0xC0
FESC = 0xDB
TFEND = 0xDC
TFESC = 0xDD
TNC_DATA = 0x00

# CSP 2.0: 48 bits, big endian. 2 priority, 14 destination, 14 source,
# 6 destination port, 6 source port, 6 flags.
CSP_HEADER_BYTES = 6
CSP_PRIO_NORM = 2
CSP_FCRC32 = 0x01

HK_PORT = 14
HK_PROTOCOL_VERSION = 1
HK_HEADER_BYTES = 10
HK_FLAG_INCOMPLETE = 0x01

# The bridge's envelope, ahead of the frame the node sent: 8 bytes of Unix
# milliseconds and 4 of sequence, which is the shape Yamcs reads a time and a
# count in. Kept in step with ENVELOPE_BYTES in hk-report.py.
ENVELOPE = struct.Struct(">QI")


def kiss_encode(frame):
    out = bytearray([FEND, TNC_DATA])
    for byte in frame:
        if byte == FEND:
            out += bytes([FESC, TFEND])
        elif byte == FESC:
            out += bytes([FESC, TFESC])
        else:
            out.append(byte)
    out.append(FEND)
    return bytes(out)


class KissReader:
    """Reassemble KISS frames from a byte stream."""

    def __init__(self):
        self._frame = bytearray()
        self._started = False
        self._escaped = False
        self._skip_type_byte = False

    def feed(self, data):
        frames = []
        for byte in data:
            if byte == FEND:
                if self._started and self._frame:
                    frames.append(bytes(self._frame))
                self._frame.clear()
                self._started = True
                self._escaped = False
                self._skip_type_byte = True
                continue
            if not self._started:
                continue
            if self._skip_type_byte:
                # The TNC command byte, which libcsp always sends as data.
                self._skip_type_byte = False
                continue
            if self._escaped:
                self._frame.append(FEND if byte == TFEND else FESC)
                self._escaped = False
            elif byte == FESC:
                self._escaped = True
            else:
                self._frame.append(byte)
        return frames


def csp_header(destination, source, dport, sport, flags):
    packed = (
        (CSP_PRIO_NORM << 46)
        | (destination << 32)
        | (source << 18)
        | (dport << 12)
        | (sport << 6)
        | flags
    )
    return packed.to_bytes(8, "big")[2:]


def parse_csp_header(frame):
    packed = int.from_bytes(b"\x00\x00" + frame[:CSP_HEADER_BYTES], "big")
    return {
        "destination": (packed >> 32) & 0x3FFF,
        "source": (packed >> 18) & 0x3FFF,
        "dport": (packed >> 12) & 0x3F,
        "sport": (packed >> 6) & 0x3F,
        "flags": packed & 0x3F,
    }


# libcsp checksums with CRC-32C (Castagnoli), not the CRC-32 in zlib. The two
# differ only in the polynomial, and a frame checked with the wrong one is
# simply dropped with nothing said, so this is worth stating rather than
# reaching for binascii and wondering why nothing answers.
CRC32C_POLYNOMIAL = 0x82F63B78
CRC32C_TABLE = []
for _index in range(256):
    _value = _index
    for _ in range(8):
        _value = (_value >> 1) ^ (CRC32C_POLYNOMIAL if _value & 1 else 0)
    CRC32C_TABLE.append(_value)


def crc32(data):
    """CRC-32C over the bytes, big endian, as csp_crc32_append writes it."""
    value = 0xFFFFFFFF
    for byte in data:
        value = CRC32C_TABLE[(value ^ byte) & 0xFF] ^ (value >> 8)
    return struct.pack(">I", value ^ 0xFFFFFFFF)


def build_request(source, destination, sport, report, count, first_age):
    """One request packet, framed exactly as libcsp would put it on the wire.

    Two CRC32s, which is not a mistake. The housekeeping socket asks for
    CSP_O_CRC32, so csp_send appends one; then the KISS interface appends
    another over what it was handed. Both cover the payload only, because the
    header is prepended after they are computed. Both are stripped on the way
    back up, so a reply that survives has been checked twice.
    """
    payload = struct.pack(">BBBH", HK_PROTOCOL_VERSION, report, count, first_age)
    payload += crc32(payload)
    body = payload + crc32(payload)
    return kiss_encode(csp_header(destination, source, HK_PORT, sport, CSP_FCRC32) + body)


def decode_hk_frame(frame, node):
    """Pull a housekeeping sample out of a CSP frame, whoever it was sent to.

    Every frame on the link passes through here, so the filter is what the
    frame *is* rather than who asked for it: anything a housekeeping server
    sent carries the server's port as its source. That covers the reply to our
    own request and, equally, one somebody else asked for — a second operator
    on the same pass, or a node that starts speaking on its own once beacons
    exist. Recording those costs nothing and asking twice costs a round trip.
    """
    if len(frame) < CSP_HEADER_BYTES + 4:
        return None, "short frame"

    header = parse_csp_header(frame)
    if header["sport"] != HK_PORT or header["source"] != node:
        # Not housekeeping, or not the node being watched. Not a fault.
        return None, None

    body = frame[CSP_HEADER_BYTES:]
    if body[-4:] != crc32(body[:-4]):
        return None, "KISS CRC32 mismatch"
    body = body[:-4]

    if header["flags"] & CSP_FCRC32:
        if len(body) < 4 or body[-4:] != crc32(body[:-4]):
            return None, "CSP CRC32 mismatch"
        body = body[:-4]

    if len(body) < HK_HEADER_BYTES:
        return None, "frame shorter than a housekeeping header"
    return body, None


def describe(sample):
    version, report, sequence, seconds, count, flags = struct.unpack_from(">BBHIBB", sample)
    when = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(seconds)) if seconds else "clock unset"
    marks = " incomplete" if flags & HK_FLAG_INCOMPLETE else ""
    return (f"report {report} seq {sequence} at {when} v{version} "
            f"{count} values{marks} {len(sample)} bytes")


def envelope(sample, host_time_ms):
    version, _report, sequence, seconds, _count, _flags = struct.unpack_from(">BBHIBB", sample)
    if version != HK_PROTOCOL_VERSION:
        raise ValueError(f"housekeeping protocol version {version}, expected {HK_PROTOCOL_VERSION}")
    # A node whose clock was never set reports zero, and stamping 1970 on it
    # would put the sample at the far end of the archive. Host time is a worse
    # answer than the node's own, and a much better one than that.
    when = seconds * 1000 if seconds else host_time_ms
    return ENVELOPE.pack(when, sequence) + sample


def collect(link, reader, args, sport, count, ask):
    """Read housekeeping off the link for a while, having asked for it or not.

    Asking is optional because the decoding is not: a frame is recognised by
    being housekeeping, so the same loop serves a poller and a listener. A
    listener adds nothing to the link, which is the whole reason to prefer one
    when something else is already asking.
    """
    if ask:
        link.reset_input_buffer()
        link.write(build_request(args.source, args.node, sport, args.report, count, 0))
        link.flush()

    samples = []
    deadline = time.monotonic() + args.timeout
    while time.monotonic() < deadline:
        # A poller stops as soon as it has what it asked for. A listener has
        # asked for nothing, so it reads until its window closes.
        if ask and len(samples) >= count:
            break
        data = link.read(link.in_waiting or 1)
        if not data:
            continue
        for frame in reader.feed(data):
            sample, problem = decode_hk_frame(frame, args.node)
            if problem:
                print(f"dropped a frame: {problem}", file=sys.stderr)
            elif sample:
                samples.append(sample)
    return samples


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--device", required=True, help="serial device or pseudo-terminal")
    parser.add_argument("--baud", type=int, default=115200)
    parser.add_argument("--node", type=int, required=True, help="CSP address of the node to ask")
    parser.add_argument("--source", type=int, default=16, help="our own CSP address")
    parser.add_argument("--sport", type=int, default=40, help="CSP source port to listen on")
    parser.add_argument("--report", type=int, default=0)
    parser.add_argument("--count", type=int, default=1, help="samples per request")
    parser.add_argument("--interval", type=float, default=5.0, help="seconds between requests")
    parser.add_argument("--timeout", type=float, default=2.0, help="seconds to wait for replies")
    parser.add_argument("--once", action="store_true", help="one request, then stop")
    parser.add_argument("--listen", action="store_true",
                        help="never ask; record the housekeeping that already crosses the link")
    parser.add_argument("--yamcs", default="127.0.0.1:10015",
                        help="host:port of the Yamcs UDP link, or 'none' to only print")
    args = parser.parse_args()

    sink = None
    if args.yamcs != "none":
        host, _, port = args.yamcs.partition(":")
        sink = (socket.socket(socket.AF_INET, socket.SOCK_DGRAM), (host, int(port)))

    reader = KissReader()
    # Bounded on purpose. A set would grow for as long as the bridge runs, and
    # sequence numbers wrap at 65536 anyway, so remembering the recent ones is
    # both cheaper and more correct than remembering all of them.
    seen = collections.deque(maxlen=1024)
    with serial.Serial(args.device, args.baud, timeout=0.1) as link:
        while True:
            samples = collect(link, reader, args, args.sport, args.count, not args.listen)
            if not samples and not args.listen:
                print("no reply", file=sys.stderr)
            for sample in samples:
                sequence = struct.unpack_from(">H", sample, 2)[0]
                if sequence in seen:
                    continue
                seen.append(sequence)
                print(describe(sample))
                if sink:
                    sink[0].sendto(envelope(sample, int(time.time() * 1000)), sink[1])
                else:
                    print(f"  {sample.hex()}")
            if args.once:
                return 0
            time.sleep(args.interval)


if __name__ == "__main__":
    sys.exit(main())
