# FRDM-K64F is currently qualified only for the K-FSW debug shell.
CONFIG_KFSW_CSP=n
CONFIG_KFSW_PARAM=n
CONFIG_KFSW_PARAM_PERSISTENCE=n
CONFIG_KFSW_FTP=n
CONFIG_KFSW_STORAGE=n

CONFIG_FLASH=n
CONFIG_FLASH_MAP=n
CONFIG_FILE_SYSTEM=n
CONFIG_FILE_SYSTEM_LITTLEFS=n
CONFIG_FILE_SYSTEM_MKFS=n

# Zephyr's OpenOCD runner consumes the Intel HEX image on this board.
CONFIG_BUILD_OUTPUT_HEX=y
